"""S4.2 — Similarity prefilter tests (ADR-003).

Two-stage check on normalized plaintext:
  Stage 1 — 128-perm MinHash on 5-word shingles (>=0.99 → reject)
  Stage 2 — per-(cik, form_type) TF-IDF cosine (>=threshold → reject)

Form 4 is excluded from similarity (universe-only per PRD §8.3 / D-014).
"""

from __future__ import annotations

import datetime as dt
import time
from pathlib import Path

import pytest

from journal.migrate import apply_migrations
from journal.models import FilingRow
from journal.repo import (
    get_similarity_cache_for_issuer_form,
    insert_filing,
)
from prefilter.similarity import (
    FormTypeNotSimilarityChecked,
    SimilarityChecker,
    SimilarityDecision,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def db_path(tmp_path: Path) -> str:
    p = tmp_path / "journal.db"
    apply_migrations(str(p))
    return str(p)


@pytest.fixture
def artifact_dir(tmp_path: Path) -> Path:
    d = tmp_path / "similarity"
    d.mkdir()
    return d


@pytest.fixture
def checker(db_path: str, artifact_dir: Path) -> SimilarityChecker:
    return SimilarityChecker(
        db_path=db_path,
        artifact_dir=str(artifact_dir),
        threshold=0.97,
    )


def _filing(
    *,
    db_path: str,
    accession: str,
    cik: int,
    form_type: str,
    raw_text_path: str = "/tmp/unused.txt",
    filed_at: dt.datetime | None = None,
) -> FilingRow:
    """Persist a `filings` row and return it with `id` populated."""
    if filed_at is None:
        filed_at = dt.datetime(2026, 4, 1, 9, 0, 0)
    row = FilingRow(
        accession_number=accession,
        cik=cik,
        form_type=form_type,
        filed_at=filed_at,
        fetched_at=filed_at + dt.timedelta(seconds=30),
        raw_text_path=raw_text_path,
        content_hash="0" * 64,
    )
    new_id = insert_filing(db_path, row)
    return row.model_copy(update={"id": new_id})


def _ten_q_template(quarter_label: str, eps: float, revenue: float) -> str:
    """A 10-Q narrative with quarter-over-quarter near-identical language.

    The vast majority of the text is shared; only quarter label, EPS, and
    revenue numbers vary. This is the canonical "TF-IDF should catch but
    MinHash may miss" scenario from ADR-003.
    """
    boilerplate = (
        "Management's discussion and analysis of financial condition and results "
        "of operations. The following discussion should be read in conjunction with "
        "the unaudited condensed consolidated financial statements and notes thereto "
        "appearing elsewhere in this quarterly report. The discussion contains "
        "forward looking statements that involve risks and uncertainties. Our actual "
        "results may differ materially from those discussed in the forward looking "
        "statements as a result of various factors including those set forth under "
        "risk factors. We design develop and sell consumer electronics including "
        "mobile devices personal computers tablets wearables and accessories. Our "
        "products are sold through our retail and online stores and through "
        "third-party cellular network carriers wholesalers retailers and resellers. "
        "Critical accounting policies and estimates the preparation of consolidated "
        "financial statements in conformity with United States generally accepted "
        "accounting principles requires management to make estimates and assumptions "
        "that affect the reported amounts of assets and liabilities the disclosure of "
        "contingent assets and liabilities at the date of the financial statements and "
        "the reported amounts of revenues and expenses during the reporting periods. "
        "The Company believes its critical accounting policies and estimates are those "
        "related to revenue recognition inventory valuation income taxes and "
        "valuation and impairment of marketable securities. Liquidity and capital "
        "resources the Company believes that its balances of cash cash equivalents "
        "and marketable securities along with cash generated by ongoing operations "
        "and continued access to debt markets will be sufficient to satisfy its cash "
        "requirements and capital return program over the next twelve months and "
        "beyond. Recent accounting pronouncements in the current year the Company "
        "adopted the standard requiring lessees to recognize most leases on the "
        "balance sheet. The adoption did not have a material impact on the "
        "consolidated financial statements. " * 4
    )
    return (
        f"For the {quarter_label} quarter, diluted earnings per share were ${eps:.2f} "
        f"and total net sales were ${revenue:.2f} billion. {boilerplate}"
    )


def _distinct_filing_text(seed: int) -> str:
    """A substantively different filing — vocabulary varies with seed.

    Uses random-like word selection seeded by `seed` to ensure successive
    seeds produce texts whose lexical overlap stays well below the TF-IDF
    cosine threshold (0.97). This avoids accidental duplicate-rejection when
    the test wants the filing to be accepted.
    """
    import random

    rng = random.Random(seed)
    vocab = [
        "aerospace", "defense", "missile", "helicopter", "pharmaceutical",
        "oncology", "trial", "regulatory", "bank", "commercial", "real",
        "estate", "charge", "office", "capital", "dividend", "software",
        "platform", "retention", "margin", "headcount", "energy", "permian",
        "bakken", "production", "guidance", "manufacturing", "automotive",
        "supplier", "logistics", "warehouse", "freight", "rail", "container",
        "shipping", "consumer", "retail", "apparel", "footwear", "luxury",
        "jewelry", "biotechnology", "vaccine", "diagnostic", "device",
        "implant", "surgery", "hospital", "insurance", "underwriting",
        "actuarial", "claims", "premium", "reserve", "mortgage", "lending",
        "deposit", "checking", "savings", "credit", "card", "merchant",
        "processing", "payment", "wallet", "fintech", "blockchain", "token",
        "exchange", "brokerage", "advisory", "wealth", "trust", "endowment",
        "pension", "annuity", "longevity", "mortality", "morbidity", "claim",
        "subrogation", "reinsurance", "excess", "umbrella", "specialty",
        "marine", "aviation", "cyber", "ransomware", "phishing", "malware",
        "endpoint", "perimeter", "firewall", "intrusion", "incident",
    ]
    body_words = [rng.choice(vocab) for _ in range(800)]
    return f"Filing seed {seed}. " + " ".join(body_words)


# ---------------------------------------------------------------------------
# AC-5 — first filing for issuer/form accepts (records minhash)
# ---------------------------------------------------------------------------


def test_first_filing_for_issuer_form_accepted(
    checker: SimilarityChecker, db_path: str
) -> None:
    f = _filing(db_path=db_path, accession="0000001-26-000001", cik=320193, form_type="10-Q")
    text = _ten_q_template("first", 1.50, 90.00)

    decision = checker.check(f, text)

    assert isinstance(decision, SimilarityDecision)
    assert decision.decision == "accept"
    assert decision.reason == "pass"
    assert decision.score is None

    cache = get_similarity_cache_for_issuer_form(db_path, 320193, "10-Q")
    assert len(cache) == 1
    assert cache[0].accession_number == f.accession_number
    assert cache[0].minhash_blob  # non-empty


# ---------------------------------------------------------------------------
# AC-2 — identical text re-filing rejects via MinHash
# ---------------------------------------------------------------------------


def test_identical_re_filing_minhash_rejects(
    checker: SimilarityChecker, db_path: str
) -> None:
    text = _ten_q_template("Q1", 1.50, 90.00)

    f1 = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    assert checker.check(f1, text).decision == "accept"

    # Same issuer, same form, identical text re-filed two days later.
    f2 = _filing(
        db_path=db_path,
        accession="0000001-26-000002",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 2, 1, 9, 0, 0),
    )
    decision = checker.check(f2, text)

    assert decision.decision == "reject"
    assert decision.reason == "minhash"
    assert decision.score is not None and decision.score >= 0.99


# ---------------------------------------------------------------------------
# AC-3 — near-identical 10-Q rejects via TF-IDF cosine
# ---------------------------------------------------------------------------


def test_near_identical_10q_tfidf_rejects(
    checker: SimilarityChecker, db_path: str
) -> None:
    """Quarter-over-quarter narrative: tiny numeric diffs, vast shared boilerplate.

    This is the ADR-003 scenario where MinHash on 5-word shingles MAY estimate
    Jaccard < 0.99 (because the shingles spanning the differing tokens differ),
    but TF-IDF cosine on 1-2 word n-grams with stopword removal stays >= 0.97.
    """
    f1 = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    text_q1 = _ten_q_template("first", 1.50, 90.00)
    assert checker.check(f1, text_q1).decision == "accept"

    f2 = _filing(
        db_path=db_path,
        accession="0000001-26-000002",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 4, 30, 9, 0, 0),
    )
    text_q2 = _ten_q_template("second", 1.55, 92.00)

    decision = checker.check(f2, text_q2)

    # We expect rejection. If MinHash catches it, that's fine; the spec lets either
    # stage fire. But the specific intent of this case is the TF-IDF path.
    assert decision.decision == "reject"
    assert decision.reason in {"minhash", "tfidf_cosine"}
    assert decision.score is not None and decision.score >= 0.97


# ---------------------------------------------------------------------------
# AC-3/4 — substantively different filing accepted
# ---------------------------------------------------------------------------


def test_substantively_different_filing_accepted(
    checker: SimilarityChecker, db_path: str
) -> None:
    f1 = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    assert checker.check(f1, _distinct_filing_text(0)).decision == "accept"

    f2 = _filing(
        db_path=db_path,
        accession="0000001-26-000002",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 4, 30, 9, 0, 0),
    )
    decision = checker.check(f2, _distinct_filing_text(1))

    assert decision.decision == "accept"
    assert decision.reason == "pass"


# ---------------------------------------------------------------------------
# AC-6 — cross-issuer comparisons do not happen
# ---------------------------------------------------------------------------


def test_cross_issuer_not_compared(
    checker: SimilarityChecker, db_path: str
) -> None:
    text = _ten_q_template("Q1", 1.50, 90.00)

    f_a = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,  # Apple
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    assert checker.check(f_a, text).decision == "accept"

    f_b = _filing(
        db_path=db_path,
        accession="0000002-26-000001",
        cik=789019,  # Microsoft (different CIK)
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    # Same form, identical text, but different issuer → no comparison → accept.
    decision = checker.check(f_b, text)
    assert decision.decision == "accept"
    assert decision.reason == "pass"


# ---------------------------------------------------------------------------
# AC-4 — vectorizer persistence (load survives restart)
# ---------------------------------------------------------------------------


def test_vectorizer_persisted_and_loaded(
    db_path: str, artifact_dir: Path
) -> None:
    chk1 = SimilarityChecker(
        db_path=db_path, artifact_dir=str(artifact_dir), threshold=0.97
    )
    f1 = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 1, 30, 9, 0, 0),
    )
    chk1.check(f1, _ten_q_template("Q1", 1.50, 90.00))

    cache = get_similarity_cache_for_issuer_form(db_path, 320193, "10-Q")
    assert len(cache) == 1
    assert Path(cache[0].tfidf_vectorizer_path).is_file()
    assert Path(cache[0].tfidf_vector_path).is_file()

    # Fresh checker (simulating process restart) loads existing artifacts.
    chk2 = SimilarityChecker(
        db_path=db_path, artifact_dir=str(artifact_dir), threshold=0.97
    )
    f2 = _filing(
        db_path=db_path,
        accession="0000001-26-000002",
        cik=320193,
        form_type="10-Q",
        filed_at=dt.datetime(2026, 4, 30, 9, 0, 0),
    )
    decision = chk2.check(f2, _ten_q_template("Q1", 1.50, 90.00))
    assert decision.decision == "reject"
    assert decision.reason == "minhash"


# ---------------------------------------------------------------------------
# AC-4 — only 5 most recent retained
# ---------------------------------------------------------------------------


def test_only_5_most_recent_retained(
    checker: SimilarityChecker, db_path: str
) -> None:
    base = dt.datetime(2026, 1, 1, 9, 0, 0)
    for i in range(7):
        f = _filing(
            db_path=db_path,
            accession=f"0000001-26-{i:06d}",
            cik=320193,
            form_type="10-Q",
            filed_at=base + dt.timedelta(days=i * 30),
        )
        # Use distinct text so each is accepted (no MinHash/TF-IDF rejection).
        checker.check(f, _distinct_filing_text(i))

    cache = get_similarity_cache_for_issuer_form(db_path, 320193, "10-Q")
    assert len(cache) == 5

    retained_accessions = {row.accession_number for row in cache}
    expected = {f"0000001-26-{i:06d}" for i in range(2, 7)}  # last 5 = i=2..6
    assert retained_accessions == expected

    # Pruned files should be gone from disk.
    for i in range(2):
        for suffix in ("vectorizer.pkl", "vector.pkl", "text.txt"):
            stale = artifact_path_for(
                base_dir=checker.artifact_dir,
                cik=320193,
                form_type="10-Q",
                accession=f"0000001-26-{i:06d}",
                suffix=suffix,
            )
            assert not stale.exists(), f"stale {stale} still on disk"


def artifact_path_for(
    *, base_dir: str, cik: int, form_type: str, accession: str, suffix: str
) -> Path:
    """Mirror SimilarityChecker's on-disk layout for retention assertions."""
    safe_form = form_type.replace("/", "_").replace(" ", "_")
    return Path(base_dir) / str(cik) / safe_form / f"{accession}.{suffix}"


# ---------------------------------------------------------------------------
# AC-7 — Form 4 raises
# ---------------------------------------------------------------------------


def test_form_4_raises(checker: SimilarityChecker, db_path: str) -> None:
    f = _filing(
        db_path=db_path,
        accession="0000001-26-000001",
        cik=320193,
        form_type="4",
    )
    with pytest.raises(FormTypeNotSimilarityChecked):
        checker.check(f, "any text at all")


# ---------------------------------------------------------------------------
# AC-8 — p95 latency on synthetic corpus
# ---------------------------------------------------------------------------


def test_p95_latency_under_5s_on_synthetic_corpus(
    checker: SimilarityChecker, db_path: str
) -> None:
    """200 synthetic 10-K-sized filings; p95 of `check()` < 5s.

    Each iteration uses a unique CIK to exercise the worst-ish case (no MinHash
    short-circuit on prior; full TF-IDF fit/transform path). A real droplet
    would benchmark differently; the test rig target is conservative per the
    story note.
    """
    base = dt.datetime(2026, 1, 1, 9, 0, 0)
    paragraph = (
        "Risk factors. Investing in the company involves a high degree of risk. "
        "You should carefully consider the following risk factors before making an "
        "investment decision. Our business operations and financial results are "
        "subject to various risks and uncertainties including those described "
        "below which could adversely affect our business financial condition and "
        "results of operations. " * 200  # ~10K-token-ish body
    )
    n = 200
    durations: list[float] = []
    for i in range(n):
        f = _filing(
            db_path=db_path,
            accession=f"0000{i:03d}-26-000001",
            cik=900000 + i,  # unique CIK per iter
            form_type="10-K",
            filed_at=base + dt.timedelta(minutes=i),
        )
        text = f"Filing number {i} {paragraph}"
        t0 = time.perf_counter()
        checker.check(f, text)
        durations.append(time.perf_counter() - t0)

    durations.sort()
    p95 = durations[int(0.95 * n) - 1]
    assert p95 < 5.0, f"p95={p95:.3f}s exceeded 5s budget"
